
  name: luneta
  version: '0.1.0'
  summary: Terminal fuzzy search tool.
  description: |
    Terminal fuzzy search tool.

  confinement: strict
  base: core18

  apps:
    luneta:
      command: luneta
    
  parts:
    luneta:
      source: https://github.com/fbeline/luneta/releases/download/v$SNAPCRAFT_PROJECT_VERSION/luneta-linux-amd64.tar.gz
      plugin: dump

  architectures:
    - build-on: amd64
      run-on: amd64
