
  name: luneta
  version: '0.3.3'
  summary: Terminal fuzzy finder
  description: |
    Luneta is an interactive filter that can be easily composed within any script.

  grade: stable
  base: core18

  apps:
    luneta:
      command: luneta
    
  parts:
    luneta:
      source: https://github.com/fbeline/luneta/releases/download/v$SNAPCRAFT_PROJECT_VERSION/luneta-linux-amd64.tar.gz
      plugin: dump
      stage-packages:
        - libncurses5

  architectures:
    - build-on: amd64
      run-on: amd64
